<?php

return [
    'restaurant_type' => [
    ['type_id' => 1, 'restaurant_id' => 151],
    ['type_id' => 2, 'restaurant_id' => 151],
    ['type_id' => 1, 'restaurant_id' => 152],
    ['type_id' => 2, 'restaurant_id' => 152],
    ['type_id' => 3, 'restaurant_id' => 153],
    ['type_id' => 5, 'restaurant_id' => 153],
    ['type_id' => 12, 'restaurant_id' => 153],
    ['type_id' => 4, 'restaurant_id' => 154],
    ['type_id' => 5, 'restaurant_id' => 154],
    ['type_id' => 12, 'restaurant_id' => 154],
    ['type_id' => 5, 'restaurant_id' => 155],
    ['type_id' => 4, 'restaurant_id' => 155],
    ['type_id' => 12, 'restaurant_id' => 155],
    ['type_id' => 6, 'restaurant_id' => 156],
    ['type_id' => 5, 'restaurant_id' => 156],
    ['type_id' => 7, 'restaurant_id' => 157],
    ['type_id' => 13, 'restaurant_id' => 157],
    ['type_id' => 8, 'restaurant_id' => 158],
    ['type_id' => 9, 'restaurant_id' => 159],
    ['type_id' => 10, 'restaurant_id' => 160],
    ['type_id' => 13, 'restaurant_id' => 160],
    ['type_id' => 11, 'restaurant_id' => 161],
    ['type_id' => 13, 'restaurant_id' => 161],
    ['type_id' => 12, 'restaurant_id' => 162],
    ['type_id' => 13, 'restaurant_id' => 163],
    ['type_id' => 14, 'restaurant_id' => 164],
    ['type_id' => 12, 'restaurant_id' => 164],
    ['type_id' => 15, 'restaurant_id' => 165],
    ['type_id' => 1, 'restaurant_id' => 166],
    ['type_id' => 2, 'restaurant_id' => 166],
    ['type_id' => 2, 'restaurant_id' => 167],
    ['type_id' => 13, 'restaurant_id' => 167],
    ['type_id' => 12, 'restaurant_id' => 168],
    ['type_id' => 8, 'restaurant_id' => 168],
    ['type_id' => 9, 'restaurant_id' => 169],
    ['type_id' => 7, 'restaurant_id' => 170],
    ['type_id' => 5, 'restaurant_id' => 171],
    ['type_id' => 4, 'restaurant_id' => 171],
    ['type_id' => 12, 'restaurant_id' => 171],
    ['type_id' => 2, 'restaurant_id' => 172],
    ['type_id' => 12, 'restaurant_id' => 172],
    ['type_id' => 13, 'restaurant_id' => 172],
    ['type_id' => 2, 'restaurant_id' => 173],
    ['type_id' => 8, 'restaurant_id' => 173],
    ['type_id' => 12, 'restaurant_id' => 174],
    ['type_id' => 13, 'restaurant_id' => 174],
    ['type_id' => 2, 'restaurant_id' => 175],
    ['type_id' => 5, 'restaurant_id' => 175],
    ['type_id' => 8, 'restaurant_id' => 175],
    ['type_id' => 2, 'restaurant_id' => 176],
    ['type_id' => 6, 'restaurant_id' => 176],
    ['type_id' => 5, 'restaurant_id' => 176],
    ['type_id' => 2, 'restaurant_id' => 178],
    ['type_id' => 10, 'restaurant_id' => 179],
    ['type_id' => 13, 'restaurant_id' => 179],
    ['type_id' => 14, 'restaurant_id' => 180],
    ['type_id' => 15, 'restaurant_id' => 181],

    ]
];