<?php

return [

    'restaurants' => [
        [
            'address' => 'Via Roma 25',
            'vat_number' => '123456789',
            'name' => 'Pizzeria da Samuele',
            'image' => 'post_images/image-pizzeria1.jpeg',
            'description' => 'Ero un programmatore ma ho deciso di fare il pizzaiolo',
            'logo' => 'post_images/logo-pizzeria1.jpeg',
        ],
        [
            'address' => 'Corso Milano 12',
            'vat_number' => '987654321',
            'name' => 'Ristorante Italiano da Luca',
            'image' => 'post_images/image-italiano1.jpeg',
            'description' => 'La migliore trattoria della città',
            'logo' => 'post_images/logo-italiano1.jpeg',
        ],
        [
            'address' => 'Via Garibaldi 10',
            'vat_number' => '192837465',
            'name' => 'Kebab Il Gusto',
            'image' => 'post_images/image-kebab1.jpeg',
            'description' => 'Un posto dove il gusto è di casa',
            'logo' => 'post_images/logo-kebab1.jpeg',
        ],
        [
            'address' => 'Piazza Duomo 5',
            'vat_number' => '564738291',
            'name' => 'Americano del Centro',
            'image' => 'post_images/image-americano1.jpeg',
            'description' => 'Cucina tipica locale',
            'logo' => 'post_images/logo-americano1.jpeg',
        ],
        [
            'address' => 'Via Dante 45',
            'vat_number' => '847362915',
            'name' => 'Hamburguer dei Sapori',
            'image' => 'post_images/image-hamburguer1.jpeg',
            'description' => 'Sapori autentici e genuini',
            'logo' => 'post_images/logo-hamburguer1.jpeg',
        ],
        [
            'address' => 'Via Verdi 22',
            'vat_number' => '726394815',
            'name' => 'Pub La Pergola',
            'image' => 'post_images/image-pub1.jpeg',
            'description' => 'Atmosfera accogliente e cibo delizioso',
            'logo' => 'post_images/logo-pub1.jpeg',
        ],
        [
            'address' => 'Via Mazzini 30',
            'vat_number' => '918273645',
            'name' => 'Poke da Marco',
            'image' => 'post_images/image-poke1.jpeg',
            'description' => 'Bistrot con piatti ricercati',
            'logo' => 'post_images/logo-poke1.jpeg',
        ],
        [
            'address' => 'Via Vittorio Emanuele 18',
            'vat_number' => '546372819',
            'name' => 'Vegetariano del Borgo',
            'image' => 'post_images/image-vegetariano1.jpeg',
            'description' => 'Un tuffo nei sapori del passato',
            'logo' => 'post_images/logo-vegetariano1.jpeg',
        ],
        [
            'address' => 'Via San Martino 11',
            'vat_number' => '657483920',
            'name' => 'Vegano Il Fornello',
            'image' => 'post_images/image-vegano1.jpeg',
            'description' => 'Trattoria tradizionale con forno a legna',
            'logo' => 'post_images/logo-vegano1.jpeg',
        ],
        [
            'address' => 'Via della Libertà 28',
            'vat_number' => '374829165',
            'name' => 'Giapponese La Piazza',
            'image' => 'post_images/image-giapponese1.jpeg',
            'description' => 'Pizza napoletana DOC',
            'logo' => 'post_images/logo-giapponese1.jpeg',
        ],
        [
            'address' => 'Via Torino 42',
            'vat_number' => '109283746',
            'name' => 'Cinese Buon Appetito',
            'image' => 'post_images/image-cinese1.jpeg',
            'description' => 'Cucina italiana tradizionale',
            'logo' => 'post_images/logo-cinese1.jpeg',
        ],
        [
            'address' => 'Via Bologna 15',
            'vat_number' => '293847561',
            'name' => 'Ristorante Carne del Sole',
            'image' => 'post_images/image-carne1.jpeg',
            'description' => 'Piatti solari e freschi',
            'logo' => 'post_images/logo-carne1.jpeg',
        ],
        [
            'address' => 'Piazza San Marco 8',
            'vat_number' => '384756192',
            'name' => 'Pesce del Mare',
            'image' => 'post_images/image-pesce1.jpeg',
            'description' => 'Specialità di pesce',
            'logo' => 'post_images/logo-pesce1.jpeg',
        ],
        [
            'address' => 'Via Firenze 27',
            'vat_number' => '475839201',
            'name' => 'Messicano di Firenze',
            'image' => 'post_images/image-messicano1.jpeg',
            'description' => 'Cucina toscana',
            'logo' => 'post_images/logo-messicano1.jpeg',
        ],
        [
            'address' => 'Via Napoli 33',
            'vat_number' => '564738291',
            'name' => 'Kosher Partenopea',
            'image' => 'post_images/image-kosher1.jpeg',
            'description' => 'Pizza napoletana tradizionale',
            'logo' => 'post_images/logo-kosher1.jpeg',
        ],
        [
            'address' => 'Via Genova 19',
            'vat_number' => '657483920',
            'name' => 'Pizzeria Ligure',
            'image' => 'post_images/image-pizzeria2.jpeg',
            'description' => 'Sapori della Liguria',
            'logo' => 'post_images/logo-pizzeria2.jpeg',
        ],
        [
            'address' => 'Via Venezia 45',
            'vat_number' => '748392615',
            'name' => 'Ristorante Veneto',
            'image' => 'post_images/image-italiano2.jpeg',
            'description' => 'Cucina veneta',
            'logo' => 'post_images/logo-italiano2.jpeg',
        ],
        [
            'address' => 'Via Palermo 37',
            'vat_number' => '837465192',
            'name' => 'Trattoria Siciliana',
            'image' => 'post_images/image-italiano1.jpeg',
            'description' => 'Sapori della Sicilia',
            'logo' => 'post_images/logo-italiano1.jpeg',
        ],
        [
            'address' => 'Via Bari 23',
            'vat_number' => '918273645',
            'name' => 'Vegano Pugliese',
            'image' => 'post_images/image-vegano2.jpeg',
            'description' => 'Cucina pugliese autentica',
            'logo' => 'post_images/logo-vegano2.jpeg',
        ],
        [
            'address' => 'Via Cagliari 29',
            'vat_number' => '102938475',
            'name' => 'Poke Sardo',
            'image' => 'post_images/image-poke2.jpeg',
            'description' => 'Specialità della Sardegna',
            'logo' => 'post_images/logo-poke2.jpeg',
        ],
        [
            'address' => 'Via Calabria 14',
            'vat_number' => '293847561',
            'name' => 'Hamburguer Calabrese',
            'image' => 'post_images/image-hamburguer2.jpeg',
            'description' => 'Sapori piccanti della Calabria',
            'logo' => 'post_images/logo-hamburguer2.jpeg',
        ],
        [
            'address' => 'Via Umbria 21',
            'vat_number' => '384756192',
            'name' => 'Ristorante Umbro',
            'image' => 'post_images/image-italiano2.jpeg',
            'description' => 'Cucina umbra tradizionale',
            'logo' => 'post_images/logo-italiano2.jpeg',
        ],
        [
            'address' => 'Via Abruzzo 11',
            'vat_number' => '475839201',
            'name' => 'Osteria Abruzzese',
            'image' => 'post_images/image-italiano1.jpeg',
            'description' => 'Sapori dell\'Abruzzo',
            'logo' => 'post_images/logo-italiano1.jpeg',
        ],
        [
            'address' => 'Via Molise 32',
            'vat_number' => '564738291',
            'name' => 'Trattoria Molisana',
            'image' => 'post_images/image-italiano2.jpeg',
            'description' => 'Cucina molisana genuina',
            'logo' => 'post_images/logo-italiano2.jpeg',
        ],
        [
            'address' => 'Via Basilicata 28',
            'vat_number' => '657483920',
            'name' => 'Ristorante Lucano',
            'image' => 'post_images/image-italiano1.jpeg',
            'description' => 'Specialità della Basilicata',
            'logo' => 'post_images/logo-italiano1.jpeg',
        ],
        [
            'address' => 'Via Friuli 17',
            'vat_number' => '748392615',
            'name' => 'Osteria Friulana',
            'image' => 'post_images/image-italiano2.jpeg',
            'description' => 'Cucina friulana',
            'logo' => 'post_images/logo-italiano2.jpeg',
        ],
        [
            'address' => 'Via Trentino 25',
            'vat_number' => '837465192',
            'name' => 'Trattoria Trentina',
            'image' => 'post_images/image-italiano1.jpeg',
            'description' => 'Sapori del Trentino',
            'logo' => 'post_images/logo-italiano1.jpeg',
        ],
        [
            'address' => 'Via Valle d\'Aosta 13',
            'vat_number' => '918273645',
            'name' => 'Ristorante Valdostano',
            'image' => 'post_images/image-italiano2.jpeg',
            'description' => 'Specialità della Valle d\'Aosta',
            'logo' => 'post_images/logo-italiano2.jpeg',
        ],
        [
            'address' => 'Via Lazio 22',
            'vat_number' => '102938475',
            'name' => 'Giapponese Romano',
            'image' => 'post_images/image-giapponese2.jpeg',
            'description' => 'Cucina giapponese nel cuore di Roma',
            'logo' => 'post_images/logo-giapponese2.jpeg',
        ],
        [
            'address' => 'Via Marche 9',
            'vat_number' => '293847561',
            'name' => 'Messicano Marchigiano',
            'image' => 'post_images/image-messicano2.jpeg',
            'description' => 'Sapori messicani nelle Marche',
            'logo' => 'post_images/logo-messicano2.jpeg',
        ],
        [
            'address' => 'Via Sardegna 16',
            'vat_number' => '384756192',
            'name' => 'Kosher Sardo',
            'image' => 'post_images/image-kosher2.jpeg',
            'description' => 'Specialità kosher dalla Sardegna',
            'logo' => 'post_images/logo-kosher2.jpeg',
        ],
        [
            'address' => 'Via Abruzzo 7',
            'vat_number' => '475839201',
            'name' => 'Trattoria Abruzzese',
            'image' => 'post_images/image-italiano1.jpeg',
            'description' => 'Cucina tradizionale dell\'Abruzzo',
            'logo' => 'post_images/logo-italiano1.jpeg',
        ],
        [
            'address' => 'Via Molise 24',
            'vat_number' => '564738291',
            'name' => 'Trattoria Molisana',
            'image' => 'post_images/image-italiano2.jpeg',
            'description' => 'Cucina molisana genuina',
            'logo' => 'post_images/logo-italiano2.jpeg',
        ],
    ]

];
