<?php

return [

   'restaurants' => [
    [
        'address' => 'Via Roma 25',
        'vat_number' => '123456789',
        'name' => 'Pizzeria da Samuele',
        'image' => 'post_images/1',
        'description' => 'Ero un programmatore ma ho deciso di fare il pizzaiolo',
        'logo' => 'post_images/2',
    ],
    [
        'address' => 'Corso Milano 12',
        'vat_number' => '987654321',
        'name' => 'Ristorante Italiano da Luca',
        'image' => 'post_images/3',
        'description' => 'La migliore trattoria della città',
        'logo' => 'post_images/4',
    ],
    [
        'address' => 'Via Garibaldi 10',
        'vat_number' => '192837465',
        'name' => 'Kebab Il Gusto',
        'image' => 'post_images/5',
        'description' => 'Un posto dove il gusto è di casa',
        'logo' => 'post_images/6',
    ],
    [
        'address' => 'Piazza Duomo 5',
        'vat_number' => '564738291',
        'name' => 'Americano del Centro',
        'image' => 'post_images/7',
        'description' => 'Cucina tipica locale',
        'logo' => 'post_images/8',
    ],
    [
        'address' => 'Via Dante 45',
        'vat_number' => '847362915',
        'name' => 'Hamburguer dei Sapori',
        'image' => 'post_images/9',
        'description' => 'Sapori autentici e genuini',
        'logo' => 'post_images/10',
    ],
    [
        'address' => 'Via Verdi 22',
        'vat_number' => '726394815',
        'name' => 'Pub La Pergola',
        'image' => 'post_images/11',
        'description' => 'Atmosfera accogliente e cibo delizioso',
        'logo' => 'post_images/12',
    ],
    [
        'address' => 'Via Mazzini 30',
        'vat_number' => '918273645',
        'name' => 'Poke da Marco',
        'image' => 'post_images/13',
        'description' => 'Bistrot con piatti ricercati',
        'logo' => 'post_images/14',
    ],
    [
        'address' => 'Via Vittorio Emanuele 18',
        'vat_number' => '546372819',
        'name' => 'Vegetariano del Borgo',
        'image' => 'post_images/15',
        'description' => 'Un tuffo nei sapori del passato',
        'logo' => 'post_images/16',
    ],
    [
        'address' => 'Via San Martino 11',
        'vat_number' => '657483920',
        'name' => 'Vegano Il Fornello',
        'image' => 'post_images/17',
        'description' => 'Trattoria tradizionale con forno a legna',
        'logo' => 'post_images/18',
    ],
    [
        'address' => 'Via della Libertà 28',
        'vat_number' => '374829165',
        'name' => 'Giapponese La Piazza',
        'image' => 'post_images/19',
        'description' => 'Pizza napoletana DOC',
        'logo' => 'post_images/20',
    ],
    [
        'address' => 'Via Torino 42',
        'vat_number' => '109283746',
        'name' => 'Cinese Buon Appetito',
        'image' => 'post_images/21',
        'description' => 'Cucina italiana tradizionale',
        'logo' => 'post_images/22',
    ],
    [
        'address' => 'Via Bologna 15',
        'vat_number' => '293847561',
        'name' => 'Ristorante Carne del Sole',
        'image' => 'post_images/23',
        'description' => 'Piatti solari e freschi',
        'logo' => 'post_images/24',
    ],
    [
        'address' => 'Piazza San Marco 8',
        'vat_number' => '384756192',
        'name' => 'Pesce del Mare',
        'image' => 'post_images/25',
        'description' => 'Specialità di pesce',
        'logo' => 'post_images/26',
    ],
    [
        'address' => 'Via Firenze 27',
        'vat_number' => '475839201',
        'name' => 'Messicano di Firenze',
        'image' => 'post_images/27',
        'description' => 'Cucina toscana',
        'logo' => 'post_images/28',
    ],
    [
        'address' => 'Via Napoli 33',
        'vat_number' => '564738291',
        'name' => 'Kosher Partenopea',
        'image' => 'post_images/29',
        'description' => 'Pizza napoletana tradizionale',
        'logo' => 'post_images/30',
    ],
    [
        'address' => 'Via Genova 19',
        'vat_number' => '657483920',
        'name' => 'Pizzeria Ligure',
        'image' => 'post_images/31',
        'description' => 'Sapori della Liguria',
        'logo' => 'post_images/32',
    ],
    [
        'address' => 'Via Venezia 45',
        'vat_number' => '748392615',
        'name' => 'Ristorante Veneto',
        'image' => 'post_images/33',
        'description' => 'Cucina veneta',
        'logo' => 'post_images/34',
    ],
    [
        'address' => 'Via Palermo 37',
        'vat_number' => '837465192',
        'name' => 'Trattoria Siciliana',
        'image' => 'post_images/35',
        'description' => 'Sapori della Sicilia',
        'logo' => 'post_images/36',
    ],
    [
        'address' => 'Via Bari 23',
        'vat_number' => '918273645',
        'name' => 'Vegano Pugliese',
        'image' => 'post_images/37',
        'description' => 'Cucina pugliese autentica',
        'logo' => 'post_images/38',
    ],
    [
        'address' => 'Via Cagliari 29',
        'vat_number' => '102938475',
        'name' => 'Poke Sardo',
        'image' => 'post_images/39',
        'description' => 'Specialità della Sardegna',
        'logo' => 'post_images/40',
    ],
    [
        'address' => 'Via Calabria 14',
        'vat_number' => '293847561',
        'name' => 'Hamburguer Calabrese',
        'image' => 'post_images/41',
        'description' => 'Sapori piccanti della Calabria',
        'logo' => 'post_images/42',
    ],
    [
        'address' => 'Via Umbria 21',
        'vat_number' => '384756192',
        'name' => 'Ristorante Umbro',
        'image' => 'post_images/43',
        'description' => 'Cucina umbra tradizionale',
        'logo' => 'post_images/44',
    ],
    [
        'address' => 'Via Abruzzo 11',
        'vat_number' => '475839201',
        'name' => 'Osteria Abruzzese',
        'image' => 'post_images/45',
        'description' => 'Sapori dell\'Abruzzo',
        'logo' => 'post_images/46',
    ],
    [
        'address' => 'Via Molise 32',
        'vat_number' => '564738291',
        'name' => 'Trattoria Molisana',
        'image' => 'post_images/47',
        'description' => 'Cucina molisana genuina',
        'logo' => 'post_images/48',
    ],
    [
        'address' => 'Via Basilicata 28',
        'vat_number' => '657483920',
        'name' => 'Ristorante Lucano',
        'image' => 'post_images/49',
        'description' => 'Specialità della Basilicata',
        'logo' => 'post_images/50',
    ],
    [
        'address' => 'Via Friuli 17',
        'vat_number' => '748392615',
        'name' => 'Osteria Friulana',
        'image' => 'post_images/51',
        'description' => 'Cucina friulana',
        'logo' => 'post_images/52',
    ],
    [
        'address' => 'Via Trentino 25',
        'vat_number' => '837465192',
        'name' => 'Trattoria Trentina',
        'image' => 'post_images/53',
        'description' => 'Sapori del Trentino',
        'logo' => 'post_images/54',
    ],
    [
        'address' => 'Via Valle d\'Aosta 13',
        'vat_number' => '918273645',
        'name' => 'Ristorante Valdostano',
        'image' => 'post_images/55',
        'description' => 'Specialità della Valle d\'Aosta',
        'logo' => 'post_images/56',
    ],
    [
        'address' => 'Via Lazio 22',
        'vat_number' => '102938475',
        'name' => 'Giapponese Romano',
        'image' => 'post_images/57',
        'description' => 'Cucina giapponese nel cuore di Roma',
        'logo' => 'post_images/58',
    ],
    [
        'address' => 'Via Marche 9',
        'vat_number' => '293847561',
        'name' => 'Messicano Marchigiano',
        'image' => 'post_images/59',
        'description' => 'Sapori messicani nelle Marche',
        'logo' => 'post_images/60',
    ],
    [
        'address' => 'Via Sardegna 16',
        'vat_number' => '384756192',
        'name' => 'Kosher Sardo',
        'image' => 'post_images/61',
        'description' => 'Specialità kosher dalla Sardegna',
        'logo' => 'post_images/62',
    ],
    [
        'address' => 'Via Abruzzo 7',
        'vat_number' => '475839201',
        'name' => 'Trattoria Abruzzese',
        'image' => 'post_images/63',
        'description' => 'Cucina tradizionale dell\'Abruzzo',
        'logo' => 'post_images/64',
    ],
    [
        'address' => 'Via Molise 24',
        'vat_number' => '564738291',
        'name' => 'Trattoria Molisana',
        'image' => 'post_images/65',
        'description' => 'Cucina molisana genuina',
        'logo' => 'post_images/66',
    ],
]


];
